name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify with Maven
        run: mvn clean verify -DskipTests
